server:
  port: 7001

spring:
  application:
    name: EUREKA-SERVER7001  #服务命名

eureka:
  instance:
        hostname: eureka7001.com    #eureka服务端的实例名称  注册中心主机名称
#    hostname: localhost
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务,
    service-url:
      #如果不写defaultZone默认使用8761访问注册中心  #注册的路径（服务器）
      #将自己的服务注册到这台机器上去
      #集群指向其它eureka
#      defaultZone: http://eureka7002.com:7002/eureka/
      #单机就是7001自己
            defaultZone: http://eureka7001.com:7001/eureka/
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
#  server:
#    关闭自我保护机制，保证不可用服务被及时踢除
#     enable-self-preservation: false
#     eviction-interval-timer-in-ms: 2000   #2秒